const STATUS_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409
};

const GET_USER_INFO_ROUTE = process.env.CONTROL_SERVER_URL + "/userInfo";

export {STATUS_CODES, GET_USER_INFO_ROUTE};
